# -*- coding: utf-8 -*-
"""covid19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c0IalqmDche5B4dLawWOA9TEhK5cdXvR

# Introduction

A pneumonia of unknown cause detected in Wuhan, China was first internationally reported from China on 31 December 2019. Today we know this virus as Coronavirus. COVID-19, which stands for COronaVIrus Disease, is the disease caused by this virus. Since then, the world has been engaged in the fight against this pandemic. Several measures have therefore been taken to "flatten the curve". We have consequently experienced social distancing, and unfortunately, many lives have been lost.

In the solidarity to face this unprecedented global crisis, several organizations did not hesitate to share several datasets allowing the conduction of various kinds of analysis in order to understand this pandemic.

# Objective

The objective of this analysis is to identify the countries with the highest number of positive cases in relation to the number of tests conducted.

# Data

You can find the data [here](https://dq-content.s3.amazonaws.com/505/covid19.csv).

# Data Exploration
"""

install.packages('readr')

library(readr)
covid_data <- read.csv("covid19.csv")

"""To understand the data, we begin by observing its dimensions, structure, and column names, as well as obtaining a general summary of the data."""

#get the dimension of the data
dimensions <- dim(covid_data)
dimensions

#check out the column names of the data
column_names <- colnames(covid_data)
column_names

#showing the first few rows of the data
head_data <- head(covid_data)
head_data

#Display summary of the data using glimpse() function
library(tibble)

glimpse_data <- glimpse(covid_data)
glimpse_data

"""# Filtering Relevant Rows"""

library(dplyr)

#filter the data to select rows with "All States" in the Province_State column, and remove the column
filtered_data <- covid_data %>%
  filter(Province_State == "All States") %>%
  select(-Province_State)

"""We can remove the "Province_State" column without losing any information because it only contains "All States" (which is not needed) after the filtering process.

# Selecting Relevant Columns
"""

selected_columns <- filtered_data %>%
  select(Date, Country_Region, active, hospitalizedCurr, daily_tested, daily_positive)

head_selected_columns <- head(selected_columns)
head_selected_columns

"""# Extracting the Top Ten countries with the highest number of tested cases"""

summary_data <- selected_columns %>%
  group_by(Country_Region) %>%
  summarise(tested = sum(daily_tested),
            positive = sum(daily_positive),
            active = sum(active),
            hospitalized = sum(hospitalizedCurr)) %>%
  arrange(desc(tested))

summary_data

top_10_countries <- head(summary_data, 10)

top_10_countries

"""# Identifying the Highest Ratio of Positive Cases to Tested Cases"""

#creating vectors
countries <- top_10_countries$Country_Region
tested_cases <- top_10_countries$tested
positive_cases <- top_10_countries$positive
active_cases <- top_10_countries$active
hospitalized_cases <- top_10_countries$hospitalized

#naming the vectors using names() function
names(positive_cases) <- countries
names(tested_cases) <- countries
names(active_cases) <- countries
names(hospitalized_cases) <- countries

#identifying the ratio of positive cases to tested cases
positive_cases

total_positive_cases <- sum(positive_cases)
total_positive_cases

average_positive_cases <- mean(positive_cases)
average_positive_cases

positive_cases_ratio <- positive_cases / total_positive_cases
positive_cases_ratio

positive_cases_ratio_to_tested <- positive_cases / tested_cases
positive_cases_ratio_to_tested

#creating a vector with the top three countries with the highest ratio of positive cases to tested cases
top_3_positive_tested_countries <- c("United Kingdom" = 0.11, "United States" = 0.1,"Turkey" = 0.08)

"""# Organizing Relevant Information"""

#creating vectors
united_kingdom <- c(0.11, 1473672, 166909, 0, 0)
united_states <- c(0.10, 17282363, 1877179, 0, 0)
turkey <- c(0.08, 2031192, 163941, 2980960, 0)

#creating a matrix
covid_matrix <- rbind(united_kingdom, united_states, turkey)

#rename the columns of the matrix
names(covid_matrix) <- c("Ratio", "Tested", "Positive", "Active", "Hospitalized")

covid_matrix

"""# Summary"""

question <- "Which countries have had the highest number of positive cases against the number of tests?"

answer <- c("Countries with the highest positive cases to tested cases ratio" = top_3_positive_tested_countries)

#creating a list of the dataframes used
dataset_list <- list(
  original_data = covid_data,
  filtered_data = filtered_data,
  selected_columns = selected_columns,
  top_10_countries = top_10_countries
)

#creating a list of matrices used
matrices_list <- list(covid_matrix)

#creating a list of vectors used
vector_list <- list(column_names, countries)

#creating a data structure that contains the lists above
data_structure_list <- list("dataframe" = dataset_list, "matrix" = matrices_list, "vector" = vector_list)

covid_analysis_list <- list(question, answer, data_structure_list)
covid_analysis_list[[2]]

"""# Conclusion

From our analysis, it is evident that the United Kingdom, United States, and Turkey are the countries with the highest number of positive cases in relation to the number of tests conducted.
"""